src/main/default/objects/Case/fields/Extraction_Status__c.field-meta.xml
<CustomField>
    <fullName>Extraction_Status__c</fullName>
    <label>Extraction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Workflow_Management_Case_Extract_Setting__c/Workflow_Management_Case_Extract_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings managing the integration with the Workflow Management platform</description>
    <label>Workflow Management Case Extract Setting</label>
</CustomObject>

src/main/default/objects/Workflow_Management_Case_Extract_Setting__c/fields/base_url__c.field-meta.xml
<CustomField>
    <fullName>base_url__c</fullName>
    <label>Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Workflow_Management_Case_Extract_Setting__c/fields/content_type__c.field-meta.xml
<CustomField>
    <fullName>content_type__c</fullName>
    <label>Content Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Workflow_Management_Case_Extract_Setting__c/fields/request_type__c.field-meta.xml
<CustomField>
    <fullName>request_type__c</fullName>
    <label>Request Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Workflow_Management_Case_Extract_Setting__c/fields/timeout__c.field-meta.xml
<CustomField>
    <fullName>timeout__c</fullName>
    <label>Timeout</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/ProcessClosedCaseBatchTest.cls
@isTest
public class ProcessClosedCaseBatchTest {

    @testSetup
    static void initializeData(){
        Workflow_Management_Case_Extract_Setting__c defaultSettings = new Workflow_Management_Case_Extract_Setting__c();
        defaultSettings.Name = 'DEFAULT';
        defaultSettings.base_url__c = 'http://mockEndpoint';
        defaultSettings.request_type__c = 'Post';
        defaultSettings.timeout__c = 5000;
        defaultSettings.content_type__c = 'application/json';
        insert defaultSettings;

        List<Account> accountRecords = AccountTestDataFactory.createAccountRecords('Individual Customer', 1, true);        
    }

    @isTest
    static void executeBatch_successTest() {
        Account acct = [SELECT Id, Name FROM Account LIMIT 1];
        System.assert(acct != null);

        List<Case> caseList = CaseTestDataFactory.createCaseRecords(acct, 100, false);
        System.assertEquals(100, caseList.size(), 'Error: incorrect number of case records');
        for(Case caseRecord : caseList) {
            caseRecord.Status = DALCase.CASE_STATUS_CLOSED;
            caseRecord.Extraction_Status__c = DALCase.EXTRACTION_STATUS_NEW;
        }
        insert caseList;

        //WMP_successMockResponse Static Resource will contain: {"success":true,"secretKey":"212"}
        StaticResourceCalloutMock successMock = new StaticResourceCalloutMock();
        successMock.setStaticResource('WMP_successMockResponse');
        successMock.setStatusCode(200);
        successMock.setHeader('Content-Type', 'application/json');
        
        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, successMock);
        Test.startTest();
            ProcessClosedCaseBatch processBatch = new ProcessClosedCaseBatch();
            Database.executeBatch(processBatch);
        Test.stopTest();

        DALCase caseDAL = new DALCase();
        List<String> validStatus = new List<String>{DALCase.CASE_STATUS_CLOSED};
        List<Case> processededCaseList = new List<Case>(caseDAL.getCaseByStatuses(validStatus));

        for(Case processedCase : processededCaseList) {
            System.assertEquals(DALCase.EXTRACTION_STATUS_PROCESSED, processedCase.Extraction_Status__c, 'Error: incorrect Extraction Status on Case record');    
        }
    }

    @isTest
    static void executeBatch_errorTest() {
        Account acct = [SELECT Id, Name FROM Account LIMIT 1];
        System.assert(acct != null);

        List<Case> caseList = CaseTestDataFactory.createCaseRecords(acct, 100, false);
        System.assertEquals(100, caseList.size(), 'Error: incorrect number of case records');
        for(Case caseRecord : caseList) {
            caseRecord.Status = DALCase.CASE_STATUS_CLOSED;
            caseRecord.Extraction_Status__c = DALCase.EXTRACTION_STATUS_NEW;
        }
        insert caseList;

        //WMP_errorMockResponse Static Resource will contain: {"success":false,"error":"error occured"}
        StaticResourceCalloutMock errorMock = new StaticResourceCalloutMock();
        errorMock.setStaticResource('WMP_errorMockResponse');
        errorMock.setStatusCode(500);
        errorMock.setHeader('Content-Type', 'application/json');
        
        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, errorMock);
        Test.startTest();
            ProcessClosedCaseBatch processBatch = new ProcessClosedCaseBatch();
            Database.executeBatch(processBatch);
        Test.stopTest();        

        DALCase caseDAL = new DALCase();
        List<String> validStatus = new List<String>{DALCase.CASE_STATUS_CLOSED};
        List<Case> processededCaseList = new List<Case>(caseDAL.getCaseByStatuses(validStatus));

        for(Case processedCase : processededCaseList) {
            System.assertEquals(DALCase.EXTRACTION_STATUS_ERROR, processedCase.Extraction_Status__c, 'Error: incorrect Extraction Status on Case record');    
        }
    }
}